# Generates src/gen_pinyin.odin + src/gen_pinyin.bin: the toneless pinyin of every CJK Unified Ideograph
# (U+4E00..U+9FFF), for search boxes that match Chinese by pinyin (search.odin).
# Run once by hand when the table should change; the output is checked in.
#
#   pip install --target <dir> pypinyin
#   PYTHONPATH=<dir> python tools/pinyin/gen_pinyin.py
#
# Data: pypinyin's pinyin_dict (from Unihan kMandarin / kHanyuPinyin), most common reading first. Up to
# MAX_READINGS distinct readings per character, so a polyphone matches by any of them (重置 chongzhi,
# 重力 zhongli). Tones are dropped and u-umlaut is written v (what people type).

import struct, unicodedata
from pypinyin.pinyin_dict import pinyin_dict

FIRST, LAST = 0x4E00, 0x9FFF
MAX_READINGS = 3

def toneless(raw):
    d = unicodedata.normalize('NFD', raw)
    umlaut = '\u0308' in d
    r = ''.join(c for c in d if not unicodedata.combining(c)).lower()   # strips tone marks and the umlaut's dots
    return r.replace('u', 'v') if umlaut else r                          # ...so put that back as v: lv, nve

syllables = []
index = {}
table = []
for cp in range(FIRST, LAST + 1):
    readings = []
    for raw in pinyin_dict.get(cp, '').split(','):
        r = toneless(raw.strip())
        if r and r.isascii() and r.isalpha() and r not in readings:
            readings.append(r)
    ids = []
    for r in readings[:MAX_READINGS]:
        if r not in index:
            index[r] = len(syllables) + 1     # 0 = none
            syllables.append(r)
        ids.append(index[r])
    table.extend(ids + [0] * (MAX_READINGS - len(ids)))

with open('src/gen_pinyin.bin', 'wb') as f:
    f.write(struct.pack('<%dH' % len(table), *table))

with open('src/gen_pinyin.odin', 'w', encoding='utf-8', newline='\n') as f:
    f.write('// AUTO GENERATED by tools/pinyin/gen_pinyin.py. DO NOT EDIT.\n\n')
    f.write('package blimp\n\n')
    f.write('PINYIN_FIRST :: 0x%04X   // the table covers the CJK Unified Ideographs block\n' % FIRST)
    f.write('PINYIN_LAST  :: 0x%04X\n' % LAST)
    f.write('PINYIN_MAX_READINGS :: %d\n\n' % MAX_READINGS)
    f.write('// Per codepoint from PINYIN_FIRST, PINYIN_MAX_READINGS indices into PINYIN_SYLLABLES, most common\n')
    f.write('// reading first (0 = none).\n')
    f.write('PINYIN_READINGS := #load("gen_pinyin.bin", []u16)\n\n')
    f.write('PINYIN_SYLLABLES := [?]string{\n    "",\n')
    for i in range(0, len(syllables), 12):
        f.write('    ' + ' '.join('"%s",' % s for s in syllables[i:i + 12]) + '\n')
    f.write('}\n')

print('pinyin: %d syllables, %d characters' % (len(syllables), sum(1 for i in range(0, len(table), MAX_READINGS) if table[i])))
