---@meta
-- AUTO GENERATED by src/codegen/codegen_lua_defs.odin from the @(lua) procs in src/. DO NOT EDIT.
-- Types for the Lua language server only; the engine never loads this file.

---@alias Anim_Pose integer   -- Odin u32
---@alias 姿态 Anim_Pose
---@alias Entity_Handle integer   -- Odin u32
---@alias 实体句柄 Entity_Handle

-- ── Anim ──

---Each update, sample and blend clips, then output one pose. A pose is valid only in the update that made it.
---@class Anim
Anim = {}

---Interpolates every joint from a to b by weight (0 = a, 1 = b). Both poses must come from the same entity.
---@param a Anim_Pose
---@param b Anim_Pose
---@param weight number
---@return Anim_Pose
function Anim.blend(a, b, weight) end

---A joint's world position and rotation, as of the entity's last pose (this update's after Anim.output).
---@param e Entity_Handle
---@param joint string
---@return Vec3 position
---@return Quat rotation
function Anim.joint(e, joint) end

---`over` on top of `base` for the named joint and everything below it (e.g. the upper body from the spine), by
---weight. The edge fades over a few joints.
---@param base Anim_Pose
---@param over Anim_Pose
---@param joint string
---@param weight number
---@return Anim_Pose
function Anim.layer(base, over, joint, weight) end

---Shows the pose on the entity this update; one per entity per update. A clip that started this update eases in
---from what was shown over about blend_time seconds. An animated entity given no pose goes back to its rest pose
---(or its `anim` clip).
---@param e Entity_Handle
---@param pose Anim_Pose
---@param blend_time? number
function Anim.output(e, pose, blend_time) end

---The clip is playing on the entity: sampled last update (or this one), and looping or not at its end. What a
---script asks instead of remembering "attacking".
---@param e Entity_Handle
---@param clip string
---@return boolean
function Anim.playing(e, clip) end

---How fast the clip travelled before import made it play in place, in metres per second at the entity's scale (0
---if it was authored in place). Playing it at speed / root_speed keeps the feet from sliding.
---@param e Entity_Handle
---@param clip string
---@return number
function Anim.root_speed(e, clip) end

---A pose of the entity's clip (the glTF animation's name) at its time, advanced by this update's dt × speed. The
---clip's time starts at 0 the first update it's sampled and is forgotten the first update it isn't. loop = false
---holds the last frame.
---@param e Entity_Handle
---@param clip string
---@param speed? number
---@param loop? boolean
---@return Anim_Pose
function Anim.sample(e, clip, speed, loop) end

---Moves a playing clip to `time` seconds without firing its events, easing in from what was shown.
---@param e Entity_Handle
---@param clip string
---@param time number
function Anim.seek(e, clip, time) end

---The playing clip's time and its length in seconds; 0, 0 if it isn't playing.
---@param e Entity_Handle
---@param clip string
---@return number time
---@return number length
function Anim.time(e, clip) end

-- ── Entity ──

---Read and write entities of the world whose script is running, by handle. An invalid handle reads zero and writes nothing.
---@class Entity
Entity = {}

---Whether `point` is inside the entity's volume (its Volume field, e.g. Trigger): the box Size covers, centred on
---the entity and turned with it. False if the handle is invalid or the entity isn't a volume. Ask each update:
---if Entity.contains(door, Entity.get_position(player)) then ... end
---@param handle Entity_Handle
---@param point Vec3
---@return boolean
function Entity.contains(handle, point) end

---A bool field by its schema id. False if the handle is invalid or the field isn't a bool.
---@param handle Entity_Handle
---@param field string
---@return boolean
function Entity.get_bool(handle, field) end

---A number field by its schema id ("intensity", "light_type"): float, integer, enum (its index) or flags (bitmask).
---0 if the handle is invalid or the field isn't a number.
---@param handle Entity_Handle
---@param field string
---@return number
function Entity.get_number(handle, field) end

---World-space position. Zero if the handle is invalid.
---@param handle Entity_Handle
---@return Vec3
function Entity.get_position(handle) end

---A quaternion field by its schema id. Identity if the handle is invalid or the field isn't a quaternion.
---@param handle Entity_Handle
---@param field string
---@return Quat
function Entity.get_quat(handle, field) end

---Rotation. Identity if the handle is invalid.
---@param handle Entity_Handle
---@return Quat
function Entity.get_rotation(handle) end

---Scale per axis. Zero if the handle is invalid.
---@param handle Entity_Handle
---@return Vec3
function Entity.get_scale(handle) end

---A text field by its schema id: "name", or an asset key like "model" or "sound". "" if the handle is invalid or the
---field isn't text.
---@param handle Entity_Handle
---@param field string
---@return string
function Entity.get_string(handle, field) end

---A vec3 field by its schema id ("velocity", "color"). Zero if the handle is invalid or the field isn't a vec3.
---@param handle Entity_Handle
---@param field string
---@return Vec3
function Entity.get_vec3(handle, field) end

---Sets Hidden: the entity isn't drawn. Collision and sound are unaffected.
---@param handle Entity_Handle
function Entity.hide(handle) end

---Hidden is set (Entity.hide). False if the handle is invalid.
---@param handle Entity_Handle
---@return boolean
function Entity.is_hidden(handle) end

---The character mover: moves the entity by `delta` as a capsule of `radius` and total `height` standing on its
---position, sliding along collision (walls stop it, slopes and steps it rides), and writes the result to its
---position. True if it ends standing on ground. delta is already scaled by dt, gravity included: Lua decides how
---things fall.
---@param handle Entity_Handle
---@param delta Vec3
---@param radius number
---@param height number
---@return boolean
function Entity.move_character(handle, delta, radius, height) end

---Plays the entity's own sound (its Sound, Volume, Range and Sound Flags), following it as it moves. False if it
---didn't start.
---@param handle Entity_Handle
---@return boolean
function Entity.play_sound(handle) end

---Turns by `by` in the entity's local space: rotation = rotation * by.
---@param handle Entity_Handle
---@param by Quat
function Entity.rotate(handle, by) end

---Writes a bool field by its schema id. Does nothing if the handle is invalid or the field isn't a bool.
---@param handle Entity_Handle
---@param field string
---@param value boolean
function Entity.set_bool(handle, field, value) end

---Writes a number field (see get_number). Does nothing if the handle is invalid or the field isn't a number.
---@param handle Entity_Handle
---@param field string
---@param value number
function Entity.set_number(handle, field, value) end

---Puts the entity at a world-space position, ignoring collision (Entity.move_character collides).
---@param handle Entity_Handle
---@param position Vec3
function Entity.set_position(handle, position) end

---Writes a quaternion field by its schema id. Does nothing if the handle is invalid or the field isn't a quaternion.
---@param handle Entity_Handle
---@param field string
---@param value Quat
function Entity.set_quat(handle, field, value) end

---Sets the rotation.
---@param handle Entity_Handle
---@param rotation Quat
function Entity.set_rotation(handle, rotation) end

---Sets the scale per axis.
---@param handle Entity_Handle
---@param scale Vec3
function Entity.set_scale(handle, scale) end

---Writes a text field by its schema id. A "name" another entity already has is made unique (name_1).
---@param handle Entity_Handle
---@param field string
---@param value string
function Entity.set_string(handle, field, value) end

---Writes a vec3 field by its schema id. Does nothing if the handle is invalid or the field isn't a vec3.
---@param handle Entity_Handle
---@param field string
---@param value Vec3
function Entity.set_vec3(handle, field, value) end

---Stops the entity's sound.
---@param handle Entity_Handle
function Entity.stop_sound(handle) end

---Moves by `delta` in world space, ignoring collision.
---@param handle Entity_Handle
---@param delta Vec3
function Entity.translate(handle, delta) end

---Clears Hidden: the entity is drawn again.
---@param handle Entity_Handle
function Entity.unhide(handle) end

---The handle still points at an entity in this world. A removed entity's handle never becomes valid again, even when
---its slot is reused.
---@param handle Entity_Handle
---@return boolean
function Entity.valid(handle) end

-- ── Game ──

---Numbers and texts the game carries across level switches (health, keys, which entry to arrive at). Each Play starts empty; Stop clears it.
---@class Game
Game = {}

---The number stored under `key`; 0 if it was never set or holds a string.
---@param key string
---@return number
function Game.get_number(key) end

---The string stored under `key`; "" if it was never set or holds a number.
---@param key string
---@return string
function Game.get_string(key) end

---Stores a number under `key` for the rest of the game, across level switches (World.switch_level).
---@param key string
---@param value number
function Game.set_number(key, value) end

---Stores a string (up to 256 bytes) under `key` for the rest of the game, across level switches.
---@param key string
---@param value string
function Game.set_string(key, value) end

-- ── Input ──

---Keyboard, mouse and gamepad. Live only in game mode (Play, or F8); otherwise keys read up and axes 0.
---@class Input
Input = {}

---The key is held. Key names are SDL scancode names: "W", "Space", "Left Shift", "Escape", "Up".
---@param key string
---@return boolean
function Input.down(key) end

---A stick (-1 to 1, +y down, dead zone removed) or trigger (0 to 1) by SDL name: "leftx", "lefty", "rightx",
---"righty", "lefttrigger", "righttrigger". 0 without a gamepad.
---@param axis string
---@return number
function Input.gamepad_axis(axis) end

---The gamepad button is held, by SDL name: "a", "b", "x", "y", "start", "leftshoulder", "dpup", "leftstick".
---@param button string
---@return boolean
function Input.gamepad_down(button) end

---The gamepad button went down this frame (names as Input.gamepad_down).
---@param button string
---@return boolean
function Input.gamepad_pressed(button) end

---Hides the cursor and keeps it in the window, for mouse look. Released while the editor has the window
---(F8 back to it, or Stop), and taken again on return.
---@param locked boolean
function Input.lock_mouse(locked) end

---How far the mouse moved this frame, in pixels (+y down). Works while the mouse is locked too.
---@return Vec2
function Input.mouse_delta() end

---The mouse button is held: 1 left, 2 middle, 3 right, 4 and 5 the side buttons.
---@param button integer
---@return boolean
function Input.mouse_down(button) end

---The mouse button went down this frame: 1 left, 2 middle, 3 right, 4 and 5 the side buttons.
---@param button integer
---@return boolean
function Input.mouse_pressed(button) end

---The key went down this frame (true for that one frame only).
---@param key string
---@return boolean
function Input.pressed(key) end

---The key went up this frame.
---@param key string
---@return boolean
function Input.released(key) end

-- ── UI ──

---The game's screen UI (text, bars, windows, buttons), live only inside the World.ui hook. Positions and sizes are fractions of the view.
---@class UI
UI = {}

---Opens a window: a panel the following widgets go in, until UI.end_window. Its point (x, y) sits at the same
---fractions of the view (0.5, 0.5 centres it; 1, 1 puts it in the bottom-right corner). `w`, `h` are fractions of the
---view; 0 fits the contents. `title` is its heading ("" for none) and tells two windows apart.
---@param title string
---@param x number
---@param y number
---@param w? number
---@param h? number
function UI.begin_window(title, x, y, w, h) end

---A button; true on the frame it's clicked.
---@param label string
---@return boolean
function UI.button(label) end

---A checkbox showing `value`; returns the value, flipped on the frame it's clicked. Store it back where it came from.
---@param label string
---@param value boolean
---@return boolean
function UI.checkbox(label, value) end

---Closes the window UI.begin_window opened.
function UI.end_window() end

---Where the next text or widget goes: its top-left at (x, y), fractions of the view from its top-left (0.5, 0.5 is
---the centre). For UI over the scene; inside a window, widgets flow top to bottom on their own.
---@param x number
---@param y number
function UI.position(x, y) end

---A bar filled to `fraction` (0 to 1): health, a timer. `w`, `h` are fractions of the view; 0 is the default, a
---quarter of the view wide and one line high. For a label, put a UI.text beside it with UI.same_line.
---@param fraction number
---@param w? number
---@param h? number
function UI.progress_bar(fraction, w, h) end

---The next text or widget goes to the right of the last one instead of below it.
function UI.same_line() end

---A horizontal rule.
function UI.separator() end

---A slider showing `value` between `min_value` and `max_value`; returns the value, changed while it's dragged. Store
---it back where it came from.
---@param label string
---@param value number
---@param min_value number
---@param max_value number
---@return number
function UI.slider(label, value, min_value, max_value) end

---A little vertical space.
function UI.spacing() end

---A line of text. `size` scales the UI font. Outside a window it gets a drop shadow, so it reads over any scene.
---@param text string
---@param color? Vec4
---@param size? number
function UI.text(text, color, size) end

-- ── World ──

---Find, add and remove entities; sounds, light groups, raycasts, debug lines.
---@class World
World = {}

---Creates an entity and returns its handle. `model` is an asset key like "assets/models/castle.gltf:flag001"; a
---`name` that's taken is made unique (name_1). Entities added during Play don't collide yet.
---@param name string
---@param model string
---@param position? Vec3
---@return Entity_Handle
function World.add(name, model, position) end

---Draws a line from `from` to `to` in every view of this world (the game view too) until the next update, so call it
---each update for as long as you want to see it: rays, paths, triggers. Depth-tested, 1 pixel, white by default.
---@param from Vec3
---@param to Vec3
---@param color? Vec4
function World.debug_line(from, to, color) end

---The entity named `name`, and whether there is one. Quiet: for when a miss is an answer (the target is gone).
---Cheap enough to call every update.
---@param name string
---@return Entity_Handle entity
---@return boolean found
function World.find(name) end

---World.find for an entity the script needs: a miss is a bug (renamed or deleted in the editor), so it warns,
---once per name per script load (the error overlay shows it), and returns an invalid handle. Use World.find when a
---miss is an answer (the target is gone).
---@param name string
---@return Entity_Handle
function World.get(name) end

---A light group's brightness without its flicker: the value set this run, else the saved one. 0 if no group has that
---name.
---@param name string
---@return number
function World.light_group(name) end

---Whether the game is paused (World.set_paused, or F6 in the editor). A paused world doesn't update, but its ui hook
---(World.ui) still runs, so that's where a pause menu goes.
---@return boolean
function World.paused() end

---Plays a sound file by its project path ("assets/sounds/jump.wav") that isn't anywhere: music, UI, the same volume
---everywhere. False if it didn't start.
---@param key string
---@param volume? number
---@return boolean
function World.play_sound(key, volume) end

---Plays a sound file at a point, fading out with distance over the default range. For something that moves, or a
---range of its own, give an entity the sound and use Entity.play_sound. False if it didn't start.
---@param key string
---@param position Vec3
---@param volume? number
---@return boolean
function World.play_sound_at(key, position, volume) end

---The first collision along the ray from `origin`, up to `distance` (direction needn't be unit length): whether it
---hit, where, the surface normal there, and the entity it belongs to.
---@param origin Vec3
---@param direction Vec3
---@param distance number
---@return boolean hit
---@return Vec3 point
---@return Vec3 normal
---@return Entity_Handle entity
function World.raycast(origin, direction, distance) end

---Removes the entity. Every handle to it becomes invalid.
---@param handle Entity_Handle
function World.remove(handle) end

---Sets a light group's brightness for this run (0 = off, 1 = as saved and baked); its flicker pattern still plays on
---top. Not saved. False if no group has that name (case-insensitive).
---@param name string
---@param brightness number
---@return boolean
function World.set_light_group(name, brightness) end

---Pauses or resumes the game: the world stops updating (its clock, physics, animation and sounds hold) until it's
---resumed. Resume from the ui hook (World.ui), which still runs while paused; update doesn't.
---@param paused boolean
function World.set_paused(paused) end

---Switches the game to another level, e.g. "assets/scenes/office.level", at the start of the next frame: this level's
---play world closes and the new level plays in its place, from its own file. Only the Game table (Game.set_number,
---Game.set_string) comes along, so write what the next level needs there first, such as which entry to arrive at.
---The level being edited is untouched, and Stop goes back to it. A path that doesn't load logs and the game plays on.
---@param path string
function World.switch_level(path) end

---Game seconds since Play; stops while paused and runs on across level switches. Animate from this, not from a
---clock kept in Lua: a level's state is what this time says, wherever the player was before.
---@return number
function World.time() end

-- ── 动画 ──

---动画：每次更新采样、混合片段，再输出一个姿态。姿态只在得到它的那次更新里有效。
---@class 动画
动画 = {}

---按 `权重` 逐个关节从 `甲` 插值到 `乙`（0 = 甲，1 = 乙）。两个姿态必须来自同一个实体。
---@param 甲 姿态
---@param 乙 姿态
---@param 权重 number
---@return 姿态
function 动画.混合(甲, 乙, 权重) end

---关节的世界位置和朝向，取自实体最后一次的姿态（在 动画.输出 之后调用就是这一帧的）。
---@param 实体 实体句柄
---@param 关节名 string
---@return Vec3ZH 位置
---@return QuatZH 朝向
function 动画.关节(实体, 关节名) end

---在关节 `关节名` 和它下面的所有关节上，用 `上` 盖住 `底`，按 `权重`
---（比如从脊椎往上挥手，腿继续走）。边界会在几个关节里渐变。
---@param 底 姿态
---@param 上 姿态
---@param 关节名 string
---@param 权重 number
---@return 姿态
function 动画.叠层(底, 上, 关节名, 权重) end

---这次更新让实体显示这个姿态，每个实体每次更新输出一个。换了片段会从刚才显示的姿态自动过渡，
---约 `过渡秒数` 秒。没有输出姿态的实体回到原始姿态（或它的 anim 字段里的片段）。
---@param 实体 实体句柄
---@param 姿态 姿态
---@param 过渡秒数? number
function 动画.输出(实体, 姿态, 过渡秒数) end

---片段是否正在这个实体上播放：上次或这次更新采样过它，并且循环或还没播到结尾。
---用它判断"正在攻击"，不要自己记状态。
---@param 实体 实体句柄
---@param 片段 string
---@return boolean
function 动画.播放中(实体, 片段) end

---导入时为了原地播放而去掉的移动速度（米/秒，已乘实体缩放）；本来就是原地制作的片段为 0。
---按 速度 / 移动速度 播放，脚就不会滑。
---@param 实体 实体句柄
---@param 片段 string
---@return number
function 动画.移动速度(实体, 片段) end

---实体的片段（glTF 里动画的名字）在它自己时间上的姿态，每次更新前进 时间差 × `速度`。
---第一次采样时从 0 开始；某次更新没采样它，时间就被丢掉，下次从头开始。`循环` 为假时停在最后一帧。
---@param 实体 实体句柄
---@param 片段 string
---@param 速度? number
---@param 循环? boolean
---@return 姿态
function 动画.采样(实体, 片段, 速度, 循环) end

---把正在播放的片段跳到第 `秒数` 秒，不触发途经的事件，并从当前显示的姿态过渡过去。
---@param 实体 实体句柄
---@param 片段 string
---@param 秒数 number
function 动画.跳转(实体, 片段, 秒数) end

---正在播放的片段的当前秒数和总长度；没在播放时返回 0, 0。
---@param 实体 实体句柄
---@param 片段 string
---@return number 秒数
---@return number 长度
function 动画.时间(实体, 片段) end

-- ── 实体 ──

---实体：按句柄读写运行中脚本所在世界的实体。句柄无效时读返回零值，写什么也不做。
---@class 实体
实体 = {}

---`点` 是否在实体的体积（它的“体积”字段，如触发区）里：Size 覆盖的盒子，以实体为中心、随实体旋转。
---句柄无效或实体不是体积时返回假。每次更新问一次：如果 实体.包含(门, 实体.取位置(玩家)) 那么 … 结束
---@param 实体 实体句柄
---@param 点 Vec3ZH
---@return boolean
function 实体.包含(实体, 点) end

---按英文字段名读布尔字段。句柄无效或不是布尔字段时返回假。
---@param 实体 实体句柄
---@param 字段 string
---@return boolean
function 实体.取布尔(实体, 字段) end

---按 schema 里的英文字段名读数字字段（如 "intensity"、"light_type"）：浮点、整数、
---枚举（序号）、标志位（位掩码）。句柄无效或不是数字字段时返回 0。
---@param 实体 实体句柄
---@param 字段 string
---@return number
function 实体.取数(实体, 字段) end

---世界坐标的位置。句柄无效时返回零矢量。
---@param 实体 实体句柄
---@return Vec3ZH
function 实体.取位置(实体) end

---按英文字段名读四元数字段。句柄无效或不是四元数字段时返回单位四元数。
---@param 实体 实体句柄
---@param 字段 string
---@return QuatZH
function 实体.取四元数(实体, 字段) end

---朝向（四元数）。句柄无效时返回单位四元数。
---@param 实体 实体句柄
---@return QuatZH
function 实体.取朝向(实体) end

---每个轴的缩放倍数。句柄无效时返回零矢量。
---@param 实体 实体句柄
---@return Vec3ZH
function 实体.取缩放(实体) end

---按英文字段名读文本字段："name"，或 "model"、"sound" 这样的资产键。句柄无效或不是文本字段时返回 ""。
---@param 实体 实体句柄
---@param 字段 string
---@return string
function 实体.取文本(实体, 字段) end

---按英文字段名读矢量3字段（如 "velocity"、"color"）。句柄无效或不是矢量3字段时返回零矢量。
---@param 实体 实体句柄
---@param 字段 string
---@return Vec3ZH
function 实体.取矢量(实体, 字段) end

---隐藏实体：不再绘制。碰撞和声音不受影响。
---@param 实体 实体句柄
function 实体.隐藏(实体) end

---是否被隐藏（见 实体.隐藏）。句柄无效时返回假。
---@param 实体 实体句柄
---@return boolean
function 实体.是否隐藏(实体) end

---角色移动：把实体当成站在它位置上的胶囊体（`半径`、总`高度`），移动 `位移`，
---沿碰撞面滑动：撞墙停下，斜坡和台阶会走上去。结果直接写进实体的位置。
---结束时站在地面上返回真。`位移` 要自己乘好时间差，重力也算在里面。
---@param 实体 实体句柄
---@param 位移 Vec3ZH
---@param 半径 number
---@param 高度 number
---@return boolean
function 实体.角色移动(实体, 位移, 半径, 高度) end

---按实体自己的 sound、volume、range、sound_flags 字段播放声音，声音跟着实体移动。没播出来返回假。
---@param 实体 实体句柄
---@return boolean
function 实体.播放声音(实体) end

---在本地坐标里转动：朝向 = 朝向 * `转动`。
---@param 实体 实体句柄
---@param 转动 QuatZH
function 实体.旋转(实体, 转动) end

---写布尔字段。句柄无效或不是布尔字段时什么也不做。
---@param 实体 实体句柄
---@param 字段 string
---@param 值 boolean
function 实体.设布尔(实体, 字段, 值) end

---写数字字段（见 取数）。句柄无效或不是数字字段时什么也不做。
---@param 实体 实体句柄
---@param 字段 string
---@param 值 number
function 实体.设数(实体, 字段, 值) end

---把实体放到世界坐标的这个位置，不管碰撞（要碰撞用 实体.角色移动）。
---@param 实体 实体句柄
---@param 位置 Vec3ZH
function 实体.设位置(实体, 位置) end

---写四元数字段。句柄无效或不是四元数字段时什么也不做。
---@param 实体 实体句柄
---@param 字段 string
---@param 值 QuatZH
function 实体.设四元数(实体, 字段, 值) end

---设置朝向（四元数）。
---@param 实体 实体句柄
---@param 朝向 QuatZH
function 实体.设朝向(实体, 朝向) end

---设置每个轴的缩放倍数。
---@param 实体 实体句柄
---@param 缩放 Vec3ZH
function 实体.设缩放(实体, 缩放) end

---写文本字段。把 "name" 改成别的实体已有的名称时，会自动改成唯一名（如 name_1）。
---@param 实体 实体句柄
---@param 字段 string
---@param 值 string
function 实体.设文本(实体, 字段, 值) end

---写矢量3字段。句柄无效或不是矢量3字段时什么也不做。
---@param 实体 实体句柄
---@param 字段 string
---@param 值 Vec3ZH
function 实体.设矢量(实体, 字段, 值) end

---停止这个实体的声音。
---@param 实体 实体句柄
function 实体.停止声音(实体) end

---位置加上 `位移`（世界坐标），不管碰撞。
---@param 实体 实体句柄
---@param 位移 Vec3ZH
function 实体.平移(实体, 位移) end

---取消隐藏，重新绘制。
---@param 实体 实体句柄
function 实体.取消隐藏(实体) end

---句柄是否还指向这个世界里的实体。实体删掉后句柄永远无效，槽位被重用也不会指向新实体。
---@param 实体 实体句柄
---@return boolean
function 实体.有效(实体) end

-- ── 游戏 ──

---游戏：切换关卡时带过去的数字和文本（血量、钥匙、从哪个入口出现）。每次运行从空开始，停止时清空。
---@class 游戏
游戏 = {}

---`键` 下存的数字；没设过或存的是文本时返回 0。
---@param 键 string
---@return number
function 游戏.取数(键) end

---`键` 下存的文本；没设过或存的是数字时返回 ""。
---@param 键 string
---@return string
function 游戏.取文本(键) end

---把数字存在 `键` 下，切换关卡（世界.切换关卡）后还在，直到这次运行结束。
---@param 键 string
---@param 值 number
function 游戏.设数(键, 值) end

---把文本（最多 256 字节）存在 `键` 下，切换关卡后还在，直到这次运行结束。
---@param 键 string
---@param 值 string
function 游戏.设文本(键, 值) end

-- ── 输入 ──

---输入：键盘、鼠标、手柄。只在游戏模式下有效（运行后，或按 F8）；其他时候按键都读作松开，轴都读作 0。
---@class 输入
输入 = {}

---这个键现在是否按着。键名是 SDL 扫描码名："W"、"Space"、"Left Shift"、"Escape"、"Up"……
---@param 键 string
---@return boolean
function 输入.按住(键) end

---摇杆（-1 到 1，+y 向下，已去死区）或扳机（0 到 1），用 SDL 名称：
---"leftx"、"lefty"、"rightx"、"righty"、"lefttrigger"、"righttrigger"。没有手柄时为 0。
---@param 轴 string
---@return number
function 输入.手柄轴(轴) end

---手柄按键是否按着，用 SDL 名称："a"、"b"、"x"、"y"、"start"、"leftshoulder"、"dpup"、"leftstick"……
---@param 按键 string
---@return boolean
function 输入.手柄按住(按键) end

---手柄按键是否在这一帧刚按下（名称同 输入.手柄按住）。
---@param 按键 string
---@return boolean
function 输入.手柄按下(按键) end

---隐藏光标并锁在窗口里，用于鼠标视角。回到编辑器时（按 F8 或停止）自动放开，回到游戏时重新锁定。
---@param 锁定 boolean
function 输入.锁定鼠标(锁定) end

---这一帧鼠标移动的像素（+y 向下）。锁定鼠标时也有效。
---@return Vec2ZH
function 输入.鼠标移动() end

---鼠标键是否按着：1 左键，2 中键，3 右键，4、5 侧键。
---@param 按键 integer
---@return boolean
function 输入.鼠标按住(按键) end

---鼠标键是否在这一帧刚按下：1 左键，2 中键，3 右键，4、5 侧键。
---@param 按键 integer
---@return boolean
function 输入.鼠标按下(按键) end

---这个键是否在这一帧刚按下（只在按下的那一帧为真）。
---@param 键 string
---@return boolean
function 输入.按下(键) end

---这个键是否在这一帧刚松开。
---@param 键 string
---@return boolean
function 输入.松开(键) end

-- ── 界面 ──

---界面：游戏的屏幕界面（文字、进度条、窗口、按钮），只在 世界.界面 回调里有效。位置和大小按视口宽高的比例算。
---@class 界面
界面 = {}

---打开一个窗口：后面的控件都放进这个面板，直到 界面.窗口结束。窗口上比例为 (x, y) 的点放在视口里同样比例的位置
---（0.5, 0.5 居中；1, 1 放在右下角）。`宽`、`高` 按视口宽高的比例算；0 是按内容自动大小。`标题` 是它的标题（"" 表示没有），
---也用来区分两个窗口。
---@param 标题 string
---@param x number
---@param y number
---@param 宽? number
---@param 高? number
function 界面.窗口开始(标题, x, y, 宽, 高) end

---一个按钮；被点击的那一帧返回真。
---@param 标签 string
---@return boolean
function 界面.按钮(标签) end

---显示 `值` 的勾选框；返回这个值，被点击的那一帧取反。把它存回原来的地方。
---@param 标签 string
---@param 值 boolean
---@return boolean
function 界面.勾选框(标签, 值) end

---关闭 界面.窗口开始 打开的窗口。
function 界面.窗口结束() end

---下一个文字或控件放在哪里：它的左上角在 (x, y)，按视口宽高的比例从左上角算（0.5, 0.5 是正中）。用于直接画在画面上的界面；
---窗口里的控件自己从上往下排。
---@param x number
---@param y number
function 界面.位置(x, y) end

---填到 `比例`（0 到 1）的进度条：血量、计时。`宽`、`高` 按视口宽高的比例算；0 是默认，视口宽度的四分之一、一行高。
---要标签就用 界面.同一行 在旁边放一个 界面.文字。
---@param 比例 number
---@param 宽? number
---@param 高? number
function 界面.进度条(比例, 宽, 高) end

---下一个文字或控件放在上一个的右边，而不是下面。
function 界面.同一行() end

---一条横线。
function 界面.分隔线() end

---显示 `值` 的滑块，范围 `最小值` 到 `最大值`；返回这个值，拖动时会变。把它存回原来的地方。
---@param 标签 string
---@param 值 number
---@param 最小值 number
---@param 最大值 number
---@return number
function 界面.滑块(标签, 值, 最小值, 最大值) end

---一点竖直的空白。
function 界面.间距() end

---一行文字。`大小` 是界面字号的倍数。不在窗口里时带阴影，画在什么背景上都看得清。
---@param 文字 string
---@param 颜色? Vec4ZH
---@param 大小? number
function 界面.文字(文字, 颜色, 大小) end

-- ── 世界 ──

---世界：查找、添加、移除实体，声音、灯光组、射线检测、调试线。
---@class 世界
世界 = {}

---新建实体，返回句柄。`模型` 是资产键，如 "assets/models/castle.gltf:flag001"；
---名称重复时自动改成 name_1 这样的唯一名。运行中新建的实体暂不参与碰撞。
---@param 名称 string
---@param 模型 string
---@param 位置? Vec3ZH
---@return 实体句柄
function 世界.添加(名称, 模型, 位置) end

---从 `起点` 到 `终点` 画一条线，这个世界的所有视口（包括游戏画面）都看得见，只保留到下一次更新，
---所以要一直看见就每次更新都画：射线、路径、触发区。有深度遮挡，1 像素宽，默认白色。
---@param 起点 Vec3ZH
---@param 终点 Vec3ZH
---@param 颜色? Vec4ZH
function 世界.调试线(起点, 终点, 颜色) end

---按名称找实体，返回句柄和是否找到。找不到时什么也不报，适合"找不到"本身就是答案的情况（比如目标已经死了）。
---很便宜，每次更新都查就行。
---@param 名称 string
---@return 实体句柄 实体
---@return boolean 找到
function 世界.查找(名称) end

---按名称取一个必须存在的实体。找不到说明它在编辑器里被改名或删掉了：在日志和错误浮层里警告
---（每个名称每次加载脚本只警告一次），返回无效句柄。找不到也正常时用 世界.查找。
---@param 名称 string
---@return 实体句柄
function 世界.获取(名称) end

---光源组当前的强度（不含闪烁）：这次运行设过就是设的值，否则是保存的值。没有这个组时返回 0。
---@param 名称 string
---@return number
function 世界.光源组(名称) end

---游戏是否暂停了（世界.设暂停，或编辑器里按 F6）。暂停的世界不更新，但它的 世界.界面 照常执行，暂停菜单就画在那里。
---@return boolean
function 世界.已暂停() end

---播放一个不在空间中的声音文件（项目路径，如 "assets/sounds/jump.wav"）：音乐、界面音效，哪里听都一样大。
---没播出来返回假。
---@param 键 string
---@param 音量? number
---@return boolean
function 世界.播放声音(键, 音量) end

---在某一点播放声音文件，按默认范围随距离衰减。会移动的东西、或要自己的范围，就把声音挂在实体上，
---用 实体.播放声音。没播出来返回假。
---@param 键 string
---@param 位置 Vec3ZH
---@param 音量? number
---@return boolean
function 世界.在位置播放声音(键, 位置, 音量) end

---从 `起点` 沿 `方向` 找第一个碰撞，最远 `距离`（方向不必是单位向量）。
---返回是否命中、命中点、表面法线和命中的实体。
---@param 起点 Vec3ZH
---@param 方向 Vec3ZH
---@param 距离 number
---@return boolean 命中
---@return Vec3ZH 点
---@return Vec3ZH 法线
---@return 实体句柄 实体
function 世界.射线检测(起点, 方向, 距离) end

---删除实体。之后指向它的句柄都无效。
---@param 实体 实体句柄
function 世界.移除(实体) end

---设置光源组这次运行的强度（0 = 关，1 = 和保存、烘焙时一样），闪烁图案照样叠加在上面。不会保存。
---没有这个名称的组（不区分大小写）时返回假。
---@param 名称 string
---@param 强度 number
---@return boolean
function 世界.设光源组(名称, 强度) end

---暂停或继续游戏：暂停后世界不再更新（时钟、物理、动画、声音都停住），直到继续。要在 世界.界面 里继续：暂停时它照常执行，
---世界.更新 不执行。
---@param 暂停 boolean
function 世界.设暂停(暂停) end

---在下一帧开始时切换到另一个关卡，如 "assets/scenes/office.level"：这个关卡的运行世界关闭，新关卡从它自己的
---文件载入接着运行。只有 游戏 表（游戏.设数、游戏.设文本）会带过去，所以先把下一关要用的写进去，比如从哪个入口出现。
---正在编辑的关卡不受影响，停止后回到它。路径载入失败会记日志，游戏照常运行。
---@param 路径 string
function 世界.切换关卡(路径) end

---运行以来的游戏秒数，暂停时停止，切换关卡时继续走。动画按它来算，不要在 Lua 里自己计时：关卡的状态就是这个时间
---对应的状态，不管玩家之前在哪里。
---@return number
function 世界.时间() end
