---@meta
-- AUTO GENERATED by src/codegen/codegen_lua_defs.odin from the @(lua) procs in src/. DO NOT EDIT.
-- Types for the Lua language server only; the engine never loads this file.

---@alias Entity_Handle integer   -- Odin u32

-- ── Entity ──

---@class Entity
Entity = {}

---@param handle Entity_Handle
---@param field string
---@return boolean
function Entity.get_bool(handle, field) end

---@param handle Entity_Handle
---@param field string
---@return number
function Entity.get_number(handle, field) end

---@param handle Entity_Handle
---@return Vec3
function Entity.get_position(handle) end

---@param handle Entity_Handle
---@param field string
---@return Quat
function Entity.get_quat(handle, field) end

---@param handle Entity_Handle
---@return Quat
function Entity.get_rotation(handle) end

---@param handle Entity_Handle
---@return Vec3
function Entity.get_scale(handle) end

---@param handle Entity_Handle
---@param field string
---@return string
function Entity.get_string(handle, field) end

---@param handle Entity_Handle
---@param field string
---@return Vec3
function Entity.get_vec3(handle, field) end

---Hidden: not drawn (entity_drawn). Collision and sound are unaffected.
---@param handle Entity_Handle
function Entity.hide(handle) end

---@param handle Entity_Handle
---@return boolean
function Entity.is_hidden(handle) end

---The character mover: moves the entity by `delta` as a capsule of `radius` and total `height` standing on its
---position, sliding along static collision (walls stop it, slopes and steps it rides). True if it ends standing on
---ground. Gravity is part of delta: Lua decides how things fall.
---@param handle Entity_Handle
---@param delta Vec3
---@param radius number
---@param height number
---@return boolean
function Entity.move_character(handle, delta, radius, height) end

---Plays the entity's own sound (its Sound, Volume, Range and Sound Flags), following it. False if it
---didn't start.
---@param handle Entity_Handle
---@return boolean
function Entity.play_sound(handle) end

---Turns by `by` in the entity's local space (rotation * by, as in the castle walkthrough).
---@param handle Entity_Handle
---@param by Quat
function Entity.rotate(handle, by) end

---@param handle Entity_Handle
---@param field string
---@param value boolean
function Entity.set_bool(handle, field, value) end

---@param handle Entity_Handle
---@param field string
---@param value number
function Entity.set_number(handle, field, value) end

---@param handle Entity_Handle
---@param position Vec3
function Entity.set_position(handle, position) end

---@param handle Entity_Handle
---@param field string
---@param value Quat
function Entity.set_quat(handle, field, value) end

---@param handle Entity_Handle
---@param rotation Quat
function Entity.set_rotation(handle, rotation) end

---@param handle Entity_Handle
---@param scale Vec3
function Entity.set_scale(handle, scale) end

---@param handle Entity_Handle
---@param field string
---@param value string
function Entity.set_string(handle, field, value) end

---@param handle Entity_Handle
---@param field string
---@param value Vec3
function Entity.set_vec3(handle, field, value) end

---@param handle Entity_Handle
function Entity.stop_sound(handle) end

---Moves by `delta` in world space.
---@param handle Entity_Handle
---@param delta Vec3
function Entity.translate(handle, delta) end

---@param handle Entity_Handle
function Entity.unhide(handle) end

---@param handle Entity_Handle
---@return boolean
function Entity.valid(handle) end

-- ── Input ──

---@class Input
Input = {}

---@param key string
---@return boolean
function Input.down(key) end

---A stick (−1 to 1, +y down, centred inside GAMEPAD_DEADZONE) or trigger (0 to 1). 0 without a gamepad.
---@param axis string
---@return number
function Input.gamepad_axis(axis) end

---@param button string
---@return boolean
function Input.gamepad_down(button) end

---@param button string
---@return boolean
function Input.gamepad_pressed(button) end

---Hides the cursor and keeps it in the window, for mouse look. Released while the editor has the window
---(F8 back to it, or Stop), and taken again on return.
---@param locked boolean
function Input.lock_mouse(locked) end

---How far the mouse moved this frame, in pixels (+y down). Works while the mouse is locked too.
---@return Vec2
function Input.mouse_delta() end

---@param button integer
---@return boolean
function Input.mouse_down(button) end

---@param button integer
---@return boolean
function Input.mouse_pressed(button) end

---@param key string
---@return boolean
function Input.pressed(key) end

---@param key string
---@return boolean
function Input.released(key) end

-- ── World ──

---@class World
World = {}

---@param name string
---@param model string
---@param position? Vec3
---@return Entity_Handle
function World.add(name, model, position) end

---Draws a line from `from` to `to` in every view of this world (the game view too) until the next frame, so
---call it each update for as long as you want to see it: rays, paths, triggers. Depth-tested, 1 pixel.
---@param from Vec3
---@param to Vec3
---@param color? Vec4
function World.debug_line(from, to, color) end

---@param name string
---@return Entity_Handle
---@return boolean
function World.find(name) end

---World.find for an entity the script needs: a miss is a bug (renamed or deleted in the editor), so it warns,
---once per name per script load (the error overlay shows it). Use World.find when a miss is an answer
---(the target is gone).
---@param name string
---@return Entity_Handle
function World.get(name) end

---A light group's scale before its flicker (the runtime value if set, else the saved one); 0 if unknown.
---@param name string
---@return number
function World.light_group(name) end

---A sound file (its project path) that isn't anywhere: music, UI, the same volume everywhere.
---@param key string
---@param volume? number
---@return boolean
function World.play_sound(key, volume) end

---A sound file at a point, fading out over SOUND_DEFAULT_RANGE. For something that moves, or a range of
---its own, give an entity the sound and use Entity.play_sound.
---@param key string
---@param position Vec3
---@param volume? number
---@return boolean
function World.play_sound_at(key, position, volume) end

---The first static collision along the ray (direction needn't be unit length), up to `distance`: whether it hit,
---where, the surface normal there, and the entity it belongs to.
---@param origin Vec3
---@param direction Vec3
---@param distance number
---@return boolean
---@return Vec3
---@return Vec3
---@return Entity_Handle
function World.raycast(origin, direction, distance) end

---@param handle Entity_Handle
function World.remove(handle) end

---Sets a light group's scale at runtime (0 = off, 1 = as saved/baked); false if no group has that name.
---@param name string
---@param scale number
---@return boolean
function World.set_light_group(name, scale) end

---Game seconds since Play (World.time): animate from this, not from a clock kept in Lua. Stops while paused.
---@return number
function World.time() end

-- ── 实体 ──

---@class 实体
实体 = {}

---@param handle Entity_Handle
---@param field string
---@return boolean
function 实体.取布尔(handle, field) end

---@param handle Entity_Handle
---@param field string
---@return number
function 实体.取数(handle, field) end

---@param handle Entity_Handle
---@return Vec3ZH
function 实体.取位置(handle) end

---@param handle Entity_Handle
---@param field string
---@return QuatZH
function 实体.取四元数(handle, field) end

---@param handle Entity_Handle
---@return QuatZH
function 实体.取朝向(handle) end

---@param handle Entity_Handle
---@return Vec3ZH
function 实体.取缩放(handle) end

---@param handle Entity_Handle
---@param field string
---@return string
function 实体.取文本(handle, field) end

---@param handle Entity_Handle
---@param field string
---@return Vec3ZH
function 实体.取矢量(handle, field) end

---Hidden: not drawn (entity_drawn). Collision and sound are unaffected.
---@param handle Entity_Handle
function 实体.隐藏(handle) end

---@param handle Entity_Handle
---@return boolean
function 实体.是否隐藏(handle) end

---The character mover: moves the entity by `delta` as a capsule of `radius` and total `height` standing on its
---position, sliding along static collision (walls stop it, slopes and steps it rides). True if it ends standing on
---ground. Gravity is part of delta: Lua decides how things fall.
---@param handle Entity_Handle
---@param delta Vec3ZH
---@param radius number
---@param height number
---@return boolean
function 实体.角色移动(handle, delta, radius, height) end

---Plays the entity's own sound (its Sound, Volume, Range and Sound Flags), following it. False if it
---didn't start.
---@param handle Entity_Handle
---@return boolean
function 实体.播放声音(handle) end

---Turns by `by` in the entity's local space (rotation * by, as in the castle walkthrough).
---@param handle Entity_Handle
---@param by QuatZH
function 实体.旋转(handle, by) end

---@param handle Entity_Handle
---@param field string
---@param value boolean
function 实体.设布尔(handle, field, value) end

---@param handle Entity_Handle
---@param field string
---@param value number
function 实体.设数(handle, field, value) end

---@param handle Entity_Handle
---@param position Vec3ZH
function 实体.设位置(handle, position) end

---@param handle Entity_Handle
---@param field string
---@param value QuatZH
function 实体.设四元数(handle, field, value) end

---@param handle Entity_Handle
---@param rotation QuatZH
function 实体.设朝向(handle, rotation) end

---@param handle Entity_Handle
---@param scale Vec3ZH
function 实体.设缩放(handle, scale) end

---@param handle Entity_Handle
---@param field string
---@param value string
function 实体.设文本(handle, field, value) end

---@param handle Entity_Handle
---@param field string
---@param value Vec3ZH
function 实体.设矢量(handle, field, value) end

---@param handle Entity_Handle
function 实体.停止声音(handle) end

---Moves by `delta` in world space.
---@param handle Entity_Handle
---@param delta Vec3ZH
function 实体.平移(handle, delta) end

---@param handle Entity_Handle
function 实体.取消隐藏(handle) end

---@param handle Entity_Handle
---@return boolean
function 实体.有效(handle) end

-- ── 输入 ──

---@class 输入
输入 = {}

---@param key string
---@return boolean
function 输入.按住(key) end

---A stick (−1 to 1, +y down, centred inside GAMEPAD_DEADZONE) or trigger (0 to 1). 0 without a gamepad.
---@param axis string
---@return number
function 输入.手柄轴(axis) end

---@param button string
---@return boolean
function 输入.手柄按住(button) end

---@param button string
---@return boolean
function 输入.手柄按下(button) end

---Hides the cursor and keeps it in the window, for mouse look. Released while the editor has the window
---(F8 back to it, or Stop), and taken again on return.
---@param locked boolean
function 输入.锁定鼠标(locked) end

---How far the mouse moved this frame, in pixels (+y down). Works while the mouse is locked too.
---@return Vec2ZH
function 输入.鼠标移动() end

---@param button integer
---@return boolean
function 输入.鼠标按住(button) end

---@param button integer
---@return boolean
function 输入.鼠标按下(button) end

---@param key string
---@return boolean
function 输入.按下(key) end

---@param key string
---@return boolean
function 输入.松开(key) end

-- ── 世界 ──

---@class 世界
世界 = {}

---@param name string
---@param model string
---@param position? Vec3ZH
---@return Entity_Handle
function 世界.添加(name, model, position) end

---Draws a line from `from` to `to` in every view of this world (the game view too) until the next frame, so
---call it each update for as long as you want to see it: rays, paths, triggers. Depth-tested, 1 pixel.
---@param from Vec3ZH
---@param to Vec3ZH
---@param color? Vec4ZH
function 世界.调试线(from, to, color) end

---@param name string
---@return Entity_Handle
---@return boolean
function 世界.查找(name) end

---World.find for an entity the script needs: a miss is a bug (renamed or deleted in the editor), so it warns,
---once per name per script load (the error overlay shows it). Use World.find when a miss is an answer
---(the target is gone).
---@param name string
---@return Entity_Handle
function 世界.获取(name) end

---A light group's scale before its flicker (the runtime value if set, else the saved one); 0 if unknown.
---@param name string
---@return number
function 世界.光源组(name) end

---A sound file (its project path) that isn't anywhere: music, UI, the same volume everywhere.
---@param key string
---@param volume? number
---@return boolean
function 世界.播放声音(key, volume) end

---A sound file at a point, fading out over SOUND_DEFAULT_RANGE. For something that moves, or a range of
---its own, give an entity the sound and use Entity.play_sound.
---@param key string
---@param position Vec3ZH
---@param volume? number
---@return boolean
function 世界.在位置播放声音(key, position, volume) end

---The first static collision along the ray (direction needn't be unit length), up to `distance`: whether it hit,
---where, the surface normal there, and the entity it belongs to.
---@param origin Vec3ZH
---@param direction Vec3ZH
---@param distance number
---@return boolean
---@return Vec3ZH
---@return Vec3ZH
---@return Entity_Handle
function 世界.射线检测(origin, direction, distance) end

---@param handle Entity_Handle
function 世界.移除(handle) end

---Sets a light group's scale at runtime (0 = off, 1 = as saved/baked); false if no group has that name.
---@param name string
---@param scale number
---@return boolean
function 世界.设光源组(name, scale) end

---Game seconds since Play (World.time): animate from this, not from a clock kept in Lua. Stops while paused.
---@return number
function 世界.时间() end
