package codegen

import "core:fmt"
import "core:slice"
import "core:strings"

// LuaLS type definitions for the @(lua) procs (completion, hover, type checks in .lua and .luacn).
// Same split as the hand-written lua_english_defs.lua / lua_chinese_defs.lua: English names on an
// English-only class (World), Chinese names on a Chinese-only class (世界), so completion never mixes
// the two. The engine never loads this file; it's read only by the language server.
generate_lua_defs :: proc(out_path: string) {
    sb: strings.Builder
    strings.builder_init(&sb)

    fmt.sbprintln(&sb, "---@meta")
    fmt.sbprintln(&sb, "-- AUTO GENERATED by src/codegen/codegen_lua_defs.odin from the @(lua) procs in src/. DO NOT EDIT.")
    fmt.sbprintln(&sb, "-- Types for the Lua language server only; the engine never loads this file.")
    fmt.sbprintln(&sb, "")
    for name, backing in codegen.int_types {
        fmt.sbprintfln(&sb, "---@alias %v integer   -- Odin %v", name, backing)
    }

    procs := sorted_values(codegen.procs)
    slice.sort_by(procs, proc(a, b: Proc_Info) -> bool {
        return a.lua_table != b.lua_table ? a.lua_table < b.lua_table : a.lua_name < b.lua_name
    })

    tables: [dynamic]string
    for p in procs do if p.lua_table != "" && !p.is_method && !slice.contains(tables[:], p.lua_table) do append(&tables, p.lua_table)

    for zh in ([]bool{false, true}) {
        for table in tables {
            global := zh ? lua_table_zh(table) : table
            if global == "" do continue
            fmt.sbprintfln(&sb, "\n-- ── %v ──\n", global)
            fmt.sbprintfln(&sb, "---@class %v", global)
            fmt.sbprintfln(&sb, "%v = {{}}", global)
            for p in procs {
                if p.lua_table != table || p.is_method do continue
                name := zh ? p.lua_name_zh : p.lua_name
                if name == "" do continue
                fmt.sbprintln(&sb, "")
                if p.docs != "" do fmt.sbprint(&sb, p.docs)
                for param in p.params {
                    fmt.sbprintfln(&sb, "---@param %v%v %v", param.name, param.default != "" ? "?" : "", lua_type(param.type, zh))
                }
                for r in p.returns do fmt.sbprintfln(&sb, "---@return %v", lua_type(r.type, zh))
                fmt.sbprintf(&sb, "function %v.%v(", global, name)
                for param, i in p.params do fmt.sbprintf(&sb, "%v%v", i > 0 ? ", " : "", param.name)
                fmt.sbprintln(&sb, ") end")
            }
        }
    }

    write_generated(out_path, strings.to_string(sb))
}

// The Chinese global for each binding table (setup.lua makes it an alias of the same table).
lua_table_zh :: proc(table: string) -> string {
    switch table {
    case "Blimp":  return "引擎"
    case "Entity": return "实体"
    case "World":  return "世界"
    case "Input":  return "输入"
    }
    return ""
}

// The LuaLS type for an Odin param/return type; FFI types use the hand-written classes (Vec3 / Vec3ZH).
lua_type :: proc(odin_type: string, zh: bool) -> string {
    switch odin_type {
    case "bool":   return "boolean"
    case "string", "cstring": return "string"
    case "f32", "f64": return "number"
    case "int", "i8", "i16", "i32", "i64", "uint", "u8", "u16", "u32", "u64": return "integer"
    }
    if info, ok := codegen.ffi_types[odin_type]; ok do return zh ? fmt.tprintf("%vZH", info.lua_global) : info.lua_global
    if odin_type in codegen.int_types do return odin_type
    if codegen.enum_types[odin_type] || codegen.flag_types[odin_type] do return "integer"
    return "any"
}

// An Odin doc comment (// lines above the proc) as LuaLS doc lines, one "---" line per comment line.
lua_doc_lines :: proc(lines: []string) -> string {
    sb: strings.Builder
    strings.builder_init(&sb)
    for line in lines {
        text := strings.trim_prefix(line, "//")
        text = strings.trim_prefix(text, " ")
        fmt.sbprintfln(&sb, "---%v", text)
    }
    return strings.to_string(sb)
}
