#pragma once

#include <math.h>
#include <string>
#include <array>
#include <vector>
#include <list>
#include <map>
#include <unordered_map>
#include <memory>
#include <functional>
#include <iostream>
#include <type_traits>
#include <assert.h>
#include <chrono>
#include <thread>
#include "math/randomc.h"
#include "standard_types.h"
#include "object/rtti.h"
#include "object/object.h"