#pragma once
#include <math.h>
#include <string>
#include <array>
#include <vector>
#include <list>
#include <unordered_map>
#include <memory>
#include <functional>
#include <iostream>
#include <type_traits>
#include <assert.h>