// AUTO GENERATED by tools/pinyin/gen_pinyin.py. DO NOT EDIT.

package blimp

PINYIN_FIRST :: 0x4E00   // the table covers the CJK Unified Ideographs block
PINYIN_LAST  :: 0x9FFF
PINYIN_MAX_READINGS :: 3

// Per codepoint from PINYIN_FIRST, PINYIN_MAX_READINGS indices into PINYIN_SYLLABLES, most common
// reading first (0 = none).
PINYIN_READINGS := #load("gen_pinyin.bin", []u16)

PINYIN_SYLLABLES := [?]string{
    "",
    "yi", "ding", "zheng", "kao", "qiao", "yu", "qi", "shang", "xia", "han", "wan", "mo",
    "zhang", "san", "ji", "bu", "fou", "fu", "mian", "gai", "chou", "zhuan", "qie", "ju",
    "cu", "pi", "shi", "qiu", "bing", "ye", "cong", "dong", "si", "cheng", "sheng", "diu",
    "liang", "you", "yan", "ban", "bang", "sang", "gun", "jiu", "ge", "gan", "ya", "qiang",
    "zhong", "jie", "feng", "guan", "kuang", "chuan", "quan", "chan", "lin", "zhuo", "zhu", "ba",
    "dan", "wei", "jing", "li", "pie", "ai", "nai", "wu", "tuo", "zhe", "me", "yao",
    "zhi", "zha", "zuo", "hu", "fa", "le", "yue", "yin", "pan", "ping", "pang", "guai",
    "jue", "mie", "nie", "xi", "xiang", "shu", "dou", "nang", "jia", "mao", "mai", "luan",
    "zi", "ru", "xue", "sha", "na", "suo", "cui", "qian", "gui", "liao", "ma", "er",
    "chu", "xu", "kui", "yun", "sui", "gen", "xuan", "geng", "xie", "zhai", "e", "tou",
    "wang", "kang", "gang", "da", "jiao", "hai", "heng", "peng", "mu", "ting", "qin", "qing",
    "bo", "zhan", "lian", "duo", "men", "ren", "shen", "ze", "jin", "nu", "pu", "reng",
    "zong", "fo", "lun", "cang", "zai", "ta", "xian", "cha", "hong", "tong", "dai", "ling",
    "chao", "chang", "sa", "fan", "miao", "yang", "ang", "bi", "wo", "jian", "mou", "fen",
    "bin", "di", "fang", "pei", "diao", "dun", "xin", "xiu", "tang", "huo", "hui", "kuai",
    "che", "chen", "xun", "bai", "gu", "ni", "zhou", "qu", "zu", "ci", "beng", "ga",
    "dian", "tian", "tan", "qia", "zhao", "shao", "ti", "ben", "he", "she", "tu", "die",
    "gou", "kou", "ning", "yong", "wa", "ka", "bao", "huai", "lao", "ming", "hen", "tiao",
    "xiao", "xing", "kan", "lai", "chi", "kua", "hua", "guang", "lie", "mi", "an", "lu",
    "gong", "cun", "lv", "zhen", "ce", "chai", "nong", "hou", "jiong", "tui", "nan", "bian",
    "pian", "chuo", "ku", "jun", "shun", "lang", "hun", "ying", "su", "lia", "pai", "biao",
    "fei", "bei", "chuang", "dao", "chui", "zhui", "kong", "juan", "luo", "song", "leng", "cai",
    "ruan", "chong", "chun", "ruo", "re", "dang", "huang", "zou", "duan", "ou", "za", "zan",
    "lou", "sou", "yuan", "rong", "jiang", "hao", "shan", "que", "nuo", "can", "ca", "lei",
    "zao", "cao", "shuang", "ao", "liu", "piao", "man", "lan", "zun", "cuan", "deng", "teng",
    "tie", "seng", "ceng", "zen", "zhuang", "min", "sai", "tai", "meng", "qiong", "la", "du",
    "long", "rang", "xiong", "dui", "ke", "wen", "rui", "nei", "shou", "ran", "gua", "mei",
    "zhun", "cou", "kai", "guo", "bie", "pao", "shua", "kei", "cuo", "pou", "po", "lve",
    "tuan", "zuan", "keng", "gao", "weng", "shuo", "tao", "pin", "nao", "zang", "suan", "te",
    "nian", "shuai", "kun", "mang", "zui", "rou", "cen", "pa", "ha", "a", "tun", "pen",
    "hang", "ne", "m", "lo", "n", "wai", "yo", "o", "sao", "hng", "ng", "huan",
    "nou", "ken", "len", "chuai", "se", "sun", "hei", "dia", "de", "dei", "kuo", "hm",
    "nin", "qun", "ri", "zeng", "en", "nv", "nuan", "niu", "rao", "niang", "shui", "nve",
    "nen", "nun", "niao", "kuan", "shuan", "zhuai", "tei", "zei", "den", "zhua", "rua", "shai",
    "run", "sen", "chua", "neng", "gei", "miu", "fiao", "ei", "shei", "zhei", "eng",
}
