package blimp

import "core:log"

// UI localization: English + Simplified Chinese, primary user is zh.
//
// Strings are static `cstring`s so ImGui consumes them with no per-frame allocation.
// The table is an enumerated array (dense enum -> direct index), not a map: O(1),
// zero-alloc, lives in rodata, and both languages sit on one row so they can't drift.
// `loc_verify` (called at UI init) fails loudly if any cell was left unfilled.
//
// Scope: user-facing UI labels only. Logs, asserts, asset keys and file paths stay
// ASCII English — they are developer diagnostics, and keys must stay portable.
//
// Window titles embed a stable `###id` suffix: ImGui derives a window's identity from
// its label, so without it a language switch would give windows new ids and reset the
// docking layout. Triple-hash `###` makes the id come *only* from the suffix (double
// `##` would still hash the visible half, so it must be `###`). Visible half translates;
// the id half never changes.
//
// This table is for fixed engine UI (menus, window titles). Entity field/flag labels are baked
// from entity_schema.ini into gen_entity.odin by codegen (entity_field_label etc.), not entries
// here. The reflection inspector still honors a `loc:<Loc_ID>` field tag as a fallback for any
// hand-authored struct that isn't schema-backed.

Lang :: enum { EN, ZH }
loc_lang: Lang = .ZH   // default to the primary (Simplified Chinese) user

Loc_ID :: enum {
    // Windows (visible###stable-id)
    Win_Schema_Editor,
    Win_Worlds,
    // Main menu
    Menu_Show,
    Menu_Entity_List,
    Menu_Entity_Inspector,
    Menu_Schema_Editor,
    Menu_Worlds,
    Menu_Language,
    Menu_Section_Entities,
    Menu_Section_Project,
    Menu_Section_Profile,
    // Worlds window
    Worlds_Open,
    Worlds_Scenes,
    Worlds_Kits,
    Worlds_None,
    Worlds_Subtitle,
    Worlds_Search,
    Worlds_Opened_Tag,
    Worlds_Kit_Tag,
    Btn_New_Viewport,
    Btn_Close,
    Btn_Refresh,
    View_Suffix,
    // Schema editor
    Schema_Save,
    Schema_Reload,
    Schema_Apply,
    Schema_Fields,
    Schema_Types,
    Schema_Add_Field,
    Schema_Add_Type,
    Schema_Rename_Hint,
    Schema_Prop_Id,
    Schema_Prop_Type,
    Schema_Prop_English,
    Schema_Prop_Chinese,
    Schema_Prop_Default,
    Schema_Prop_Name,
    Schema_Kind,
    Schema_Kind_Enum,
    Schema_Kind_Flags,
    Schema_Kind_Struct,
    Schema_Members,
    Schema_Move_Up,
    Schema_Move_Down,
    Schema_Remove,
    Schema_Add_Member,
    Schema_Remove_Type,
    Schema_Builtin,
    Schema_Status_Saved,
    Schema_Status_Reloaded,
    Schema_Status_Build_Failed,

    Btn_Paste_Over,
    Btn_Paste,
    Asset_None,
    Btn_Save_Level,
    Tool_Select,
    Tool_Move,
    Tool_Rotate,
    Tool_Scale,
    Tool_Snap,
    Tool_Snap_Tip,
    Tool_Space_Global,
    Tool_Space_Local,
    Tool_Space_Tip,
    Tool_Pivot_Center,
    Tool_Pivot_Individual,
    Tool_Pivot_Tip,
    Save_No_Changes,
    Unsaved_Title,
    Unsaved_World_Msg,
    Unsaved_Quit_Msg,
    Btn_Save_Changes,
    Btn_Save_All,
    Btn_Dont_Save,
    Btn_Cancel,
    Inspector_Multi,
    Win_World_Settings,
    World_Background,
    World_Exposure,
    World_Shading,
    World_Script,
    World_Sky_Color,
    World_Sky_Intensity,
    World_Probe_Spacing,
    Btn_Bake_Probes,
    Bake_Status,
    Bake_None,
    Tool_Show_Probes,
    World_Light_Groups,
    Light_Group_Name,
    Light_Group_Scale,
    Light_Group_Pattern,
    Light_Group_1,
    Light_Group_2,
    Light_Group_3,
    Light_Group_4,
    Lighting_Groups,
    Lighting_Groups_Reset,
    Win_Bake,
    Win_Retro,
    Retro_PS1,
    Retro_CRT,
    Retro_On,
    Retro_Low_Res,
    Retro_Lines,
    Retro_Lines_Tip,
    Retro_Vertex_Snap,
    Retro_Snap,
    Retro_Affine,
    Retro_Warp,
    Retro_Point_Sampling,
    Retro_Quantize,
    Retro_Color_Bits,
    Retro_Dither,
    Retro_Composite,
    Retro_Luma_Blur,
    Retro_Chroma_Blur,
    Retro_Scanlines,
    Retro_Strength,
    Retro_Beam_Dark,
    Retro_Beam_Bright,
    Retro_Mask,
    Retro_Bloom,
    Retro_Radius,
    Retro_Tube,
    Retro_Gamma,
    Retro_Gamma_Tip,
    Retro_Brightness,
    Retro_Clean_Note,
    Btn_Retro_Defaults,
    Bake_Last,
    Bake_Atlas,
    Bake_Atlas_Tip,
    Bake_Section_Quality,
    Bake_Section_Sky,
    Bake_Section_Grid,
    Bake_Quality,
    Bake_Quality_Draft,
    Bake_Quality_Medium,
    Bake_Quality_High,
    Bake_Quality_Custom,
    Bake_Rays,
    Bake_Bounces,
    Bake_Sky,
    Bake_Bounds,
    Bake_Bounds_Auto,
    Bake_Bounds_Manual,
    Bake_Bounds_Min,
    Bake_Bounds_Max,
    Btn_Bake_Fit,
    Bake_Estimate,
    Tool_Lighting,
    Lighting_Lit,
    Lighting_Probes_Only,
    Lighting_Indirect_Only,
    Lighting_Direct_Only,
    Lighting_Lighting_Only,
    Lighting_Use_Probes,
    Lighting_Indirect_Scale,
    Lighting_Reset,
    Win_Game_Settings,
    Menu_Game_Settings,
    Game_Start_Level,
    // Templates window
    Win_Templates,
    Menu_Templates,
    Templates_Hint,
    Templates_No_World,
    Btn_Edit_Templates,
    // Template names: Template_<name field>, looked up by name (ui_templates.odin)
    Template_empty,
    Template_marker,
    Template_point_light,
    Template_point_light_shadow,
    Template_spot_light,
    Template_spot_light_shadow,
    Template_cylinder_light,
    Template_sun,
    Template_camera,
    Template_ortho_camera,
    // Entity panels
    Panel_Follow,
    Inspector_Kit_Warning,
    Panel_No_World,
    // GPU Resources window
    Win_Resources,
    Menu_Resources,
    Res_Kind_Texture,
    Res_Kind_Geometry,
    Res_Kind_Table,
    Res_Kind_Probes,
    Res_Kind_Frame_Data,
    Res_Kind_Target,
    Res_Owner_Assets,
    Res_Owner_View,
    Res_Owner_Engine,
    Res_Flights,
    Res_Transforms,
    Res_Mesh_Instances,
    Res_Lights,
    Res_Draw_Commands,
    Res_Shadow_Maps,
    Res_Shadow_Views,
    Res_Probes,
    Res_Probe_Depth,
    Res_Display_Target,
    Res_Scene_Target,
    Res_Depth_Target,
    Res_Frame_Constants,
    Res_Swapchain,
    Res_Debug_Lines,
    Res_Count,
    Asset_Shared,
    Asset_Mesh_Detail,
    Asset_Mesh_Table,
    Asset_Material_Table,
    // Entity right-click menu
    Ctx_Copy,
    Ctx_Paste,
    Ctx_Duplicate,
    Ctx_Delete,
    Ctx_Select_All,
    Ctx_Deselect,
    Ctx_Frame,
    Ctx_Hide,
    Ctx_Unhide_All,
    // Play mode
    Play_Play,
    Play_Stop,
    Play_Pause,
    Play_No_Save,
    Play_Warning,
    Worlds_Playing_Tag,
    Ctx_Rename,
    Tool_Maximize,
    Play_Step,
    Tool_Game_View,
    Tool_Retro_Look,
    Tool_Edit_Script,
}

@(rodata)
loc_text := [Loc_ID][Lang]cstring {
    .Win_Schema_Editor     = { .EN = "Schema Editor###schema_editor",       .ZH = "结构编辑器###schema_editor" },
    .Win_Worlds            = { .EN = "Worlds###worlds",                     .ZH = "世界###worlds" },

    .Menu_Show             = { .EN = "Show",             .ZH = "显示" },
    .Menu_Entity_List      = { .EN = "Entity List",      .ZH = "实体列表" },
    .Menu_Entity_Inspector = { .EN = "Entity Inspector", .ZH = "实体检查器" },
    .Menu_Schema_Editor    = { .EN = "Schema Editor",    .ZH = "结构编辑器" },
    .Menu_Worlds           = { .EN = "Worlds",           .ZH = "世界" },
    .Menu_Language         = { .EN = "Language",         .ZH = "语言" },
    .Menu_Section_Entities = { .EN = "ENTITIES",         .ZH = "实体" },
    .Menu_Section_Project  = { .EN = "PROJECT",          .ZH = "项目" },
    .Menu_Section_Profile  = { .EN = "PROFILE",          .ZH = "性能分析" },

    .Worlds_Open      = { .EN = "Open Worlds",   .ZH = "已打开的世界" },
    .Worlds_Scenes    = { .EN = "Scenes",        .ZH = "场景" },
    .Worlds_Kits      = { .EN = "Kits (glTF)",   .ZH = "套件 (glTF)" },
    .Worlds_None      = { .EN = "(none found)",  .ZH = "（未找到）" },
    .Worlds_Subtitle   = { .EN = "Open a scene to edit, or a kit to browse and copy models from.", .ZH = "打开场景进行编辑，或打开套件浏览并复制模型。" },
    .Worlds_Search     = { .EN = "Search scenes and kits", .ZH = "搜索场景和套件" },
    .Worlds_Opened_Tag = { .EN = "open",   .ZH = "已打开" },
    .Worlds_Kit_Tag    = { .EN = "kit", .ZH = "套件" },   // open-worlds panel: this world is a kit (not saved)
    .Btn_New_Viewport = { .EN = "New Viewport",  .ZH = "新视口" },
    .Btn_Close        = { .EN = "Close",         .ZH = "关闭" },
    .Btn_Refresh      = { .EN = "Refresh",       .ZH = "刷新" },
    .View_Suffix      = { .EN = "Viewport",      .ZH = "视口" },   // "<world title> 视口" on every view window

    .Schema_Save      = { .EN = "Save",            .ZH = "保存" },
    .Schema_Reload    = { .EN = "Reload",          .ZH = "重新加载" },
    .Schema_Apply     = { .EN = "Apply & Restart", .ZH = "应用并重启" },
    .Schema_Fields    = { .EN = "Fields",          .ZH = "字段" },
    .Schema_Types     = { .EN = "Types",           .ZH = "类型" },
    .Schema_Add_Field = { .EN = "Add Field",       .ZH = "添加字段" },
    .Schema_Add_Type  = { .EN = "Add Type",        .ZH = "添加类型" },

    .Schema_Rename_Hint  = { .EN = "Renaming a field id orphans that field's data in existing scenes.",
                             .ZH = "重命名字段 ID 会使现有场景中该字段的数据失效。" },
    .Schema_Prop_Id      = { .EN = "ID",       .ZH = "ID" },
    .Schema_Prop_Type    = { .EN = "Type",     .ZH = "类型" },
    .Schema_Prop_English = { .EN = "English",  .ZH = "英文" },
    .Schema_Prop_Chinese = { .EN = "Chinese",  .ZH = "中文" },
    .Schema_Prop_Default = { .EN = "Default",  .ZH = "默认值" },
    .Schema_Prop_Name    = { .EN = "Name",     .ZH = "名称" },
    .Schema_Kind         = { .EN = "Kind",     .ZH = "种类" },
    .Schema_Kind_Enum    = { .EN = "Enum",           .ZH = "枚举" },
    .Schema_Kind_Flags   = { .EN = "Bit set (flags)", .ZH = "位集合（标志）" },
    .Schema_Kind_Struct  = { .EN = "Struct",         .ZH = "结构体" },
    .Schema_Members      = { .EN = "Members",  .ZH = "成员" },
    .Schema_Move_Up      = { .EN = "Up",       .ZH = "上移" },
    .Schema_Move_Down    = { .EN = "Down",     .ZH = "下移" },
    .Schema_Remove       = { .EN = "Remove",   .ZH = "删除" },
    .Schema_Add_Member   = { .EN = "Add Member",  .ZH = "添加成员" },
    .Schema_Remove_Type  = { .EN = "Remove Type", .ZH = "删除类型" },
    .Schema_Builtin      = { .EN = "built-in", .ZH = "内置" },

    .Schema_Status_Saved        = { .EN = "Saved.",                      .ZH = "已保存。" },
    .Schema_Status_Reloaded     = { .EN = "Reloaded from disk.",         .ZH = "已从磁盘重新加载。" },
    .Schema_Status_Build_Failed = { .EN = "Build failed — see console.", .ZH = "编译失败 — 请查看控制台。" },

    .Btn_Paste_Over = { .EN = "Paste Over", .ZH = "覆盖粘贴" },
    .Btn_Paste      = { .EN = "Paste",      .ZH = "粘贴" },   // paste one field from the clipboard
    .Asset_None     = { .EN = "(none)",     .ZH = "（无）" },   // an asset picker's empty choice
    .Btn_Save_Level = { .EN = "Save",       .ZH = "保存" },   // viewport toolbar: write the world to its scene file
    .Tool_Select    = { .EN = "Select",     .ZH = "选择" },   // viewport toolbar tools
    .Tool_Move      = { .EN = "Move",       .ZH = "移动" },
    .Tool_Rotate    = { .EN = "Rotate",     .ZH = "旋转" },
    .Tool_Scale     = { .EN = "Scale",      .ZH = "缩放" },
    .Tool_Snap      = { .EN = "Snap",       .ZH = "吸附" },
    .Tool_Snap_Tip  = { .EN = "Hold Ctrl while dragging to invert", .ZH = "拖动时按住 Ctrl 临时反转" },
    .Tool_Space_Global = { .EN = "Global", .ZH = "全局" },
    .Tool_Space_Local  = { .EN = "Local",  .ZH = "局部" },
    .Tool_Space_Tip    = { .EN = "Move/rotate along world axes or the object's own (scale is always local)", .ZH = "移动/旋转沿世界坐标轴或物体自身坐标轴（缩放始终为局部）" },
    .Tool_Pivot_Center     = { .EN = "Center", .ZH = "中心" },
    .Tool_Pivot_Individual = { .EN = "Pivots", .ZH = "各自" },
    .Tool_Pivot_Tip        = { .EN = "Rotate/scale a multi-selection as one group about its centre, or each object about its own pivot", .ZH = "旋转/缩放多个对象时：整体绕选择中心，或各自绕自身轴心" },
    .Save_No_Changes   = { .EN = "No unsaved changes", .ZH = "没有未保存的更改" },
    .Unsaved_Title     = { .EN = "Unsaved Changes",    .ZH = "未保存的更改" },
    .Unsaved_World_Msg = { .EN = "has unsaved changes.", .ZH = "有未保存的更改。" },   // after the scene name
    .Unsaved_Quit_Msg  = { .EN = "These scenes have unsaved changes:", .ZH = "以下场景有未保存的更改：" },
    .Btn_Save_Changes  = { .EN = "Save",       .ZH = "保存" },
    .Btn_Save_All      = { .EN = "Save All",   .ZH = "全部保存" },
    .Btn_Dont_Save     = { .EN = "Don't Save", .ZH = "不保存" },
    .Btn_Cancel        = { .EN = "Cancel",     .ZH = "取消" },
    .Inspector_Multi   = { .EN = "%d selected (showing the active one)", .ZH = "已选择 %d 个（显示当前活动对象）" },
    .Win_World_Settings = { .EN = "World Settings", .ZH = "世界设置" },
    .World_Background   = { .EN = "Background",     .ZH = "背景色" },
    .World_Exposure     = { .EN = "Exposure (EV)",  .ZH = "曝光 (EV)" },
    .World_Shading      = { .EN = "Shading",        .ZH = "着色" },
    .World_Script       = { .EN = "Lua Script",     .ZH = "Lua 脚本" },
    .World_Sky_Color     = { .EN = "Sky Colour",        .ZH = "天空颜色" },
    .Bake_Section_Quality = { .EN = "Quality",          .ZH = "质量" },
    .Bake_Section_Sky    = { .EN = "Sky",               .ZH = "天空" },
    .Bake_Section_Grid   = { .EN = "Probe Grid",        .ZH = "探针网格" },
    .Bake_Quality        = { .EN = "Preset",            .ZH = "预设" },
    .Bake_Quality_Draft  = { .EN = "Draft",             .ZH = "草稿" },
    .Bake_Quality_Medium = { .EN = "Medium",            .ZH = "中" },
    .Bake_Quality_High   = { .EN = "High",              .ZH = "高" },
    .Bake_Quality_Custom = { .EN = "Custom",            .ZH = "自定义" },
    .Bake_Rays           = { .EN = "Rays per Probe",    .ZH = "每探针光线数" },
    .Bake_Bounces        = { .EN = "Bounces",           .ZH = "反弹次数" },
    .Bake_Sky            = { .EN = "Include Sky",       .ZH = "包含天空" },
    .Bake_Bounds         = { .EN = "Bounds",            .ZH = "范围" },
    .Bake_Bounds_Auto    = { .EN = "Auto (static geometry)", .ZH = "自动（静态几何体）" },
    .Bake_Bounds_Manual  = { .EN = "Manual box",        .ZH = "手动包围盒" },
    .Bake_Bounds_Min     = { .EN = "Box Min",           .ZH = "包围盒最小值" },
    .Bake_Bounds_Max     = { .EN = "Box Max",           .ZH = "包围盒最大值" },
    .Btn_Bake_Fit        = { .EN = "Fit to Geometry",   .ZH = "适配几何体" },
    .Bake_Estimate       = { .EN = "%d probes (max %d)", .ZH = "%d 个探针（上限 %d）" },
    .World_Sky_Intensity = { .EN = "Sky Intensity",     .ZH = "天空强度" },
    .World_Probe_Spacing = { .EN = "Probe Spacing (m)", .ZH = "探针间距（米）" },
    .Btn_Bake_Probes     = { .EN = "Bake Probes",       .ZH = "烘焙探针" },
    .Bake_Status         = { .EN = "%d × %d × %d probes, %d layers", .ZH = "%d × %d × %d 个探针，%d 层" },
    .Bake_None           = { .EN = "Not baked",         .ZH = "未烘焙" },
    .Tool_Show_Probes    = { .EN = "Show Probes",       .ZH = "显示探针" },
    .World_Light_Groups  = { .EN = "Light Groups",      .ZH = "光源组" },
    .Light_Group_Name    = { .EN = "Name",              .ZH = "名称" },
    .Light_Group_Scale   = { .EN = "Intensity ×",       .ZH = "强度倍数" },
    .Light_Group_Pattern = { .EN = "Flicker (a–z)",     .ZH = "闪烁（a–z）" },
    .Light_Group_1       = { .EN = "Group 1",           .ZH = "组 1" },
    .Light_Group_2       = { .EN = "Group 2",           .ZH = "组 2" },
    .Light_Group_3       = { .EN = "Group 3",           .ZH = "组 3" },
    .Light_Group_4       = { .EN = "Group 4",           .ZH = "组 4" },
    .Lighting_Groups     = { .EN = "Light groups (this world, runtime)", .ZH = "光源组（当前世界，运行时）" },
    .Lighting_Groups_Reset = { .EN = "Back to saved",   .ZH = "恢复保存值" },
    .Win_Bake            = { .EN = "Probe Bake",        .ZH = "探针烘焙" },
    .Win_Retro           = { .EN = "Retro Look",        .ZH = "复古效果" },
    .Retro_PS1           = { .EN = "PS1",               .ZH = "PS1" },
    .Retro_CRT           = { .EN = "CRT",               .ZH = "CRT" },
    .Retro_On            = { .EN = "On",                .ZH = "启用" },
    .Retro_Low_Res       = { .EN = "Low resolution",    .ZH = "低分辨率" },
    .Retro_Lines         = { .EN = "Lines",             .ZH = "行数" },
    .Retro_Lines_Tip     = { .EN = "The scene height to aim for. It upscales by the whole number that comes closest, so the real height depends on the view's size.", .ZH = "目标场景高度。按最接近的整数倍放大，因此实际高度取决于视图大小。" },
    .Retro_Vertex_Snap   = { .EN = "Vertex jitter",     .ZH = "顶点抖动" },
    .Retro_Snap          = { .EN = "Grid (pixels)",     .ZH = "网格（像素）" },
    .Retro_Affine        = { .EN = "Affine textures",   .ZH = "仿射纹理" },
    .Retro_Warp          = { .EN = "Warp",              .ZH = "扭曲" },
    .Retro_Point_Sampling = { .EN = "Point sampling",   .ZH = "点采样" },
    .Retro_Quantize      = { .EN = "Colour depth",      .ZH = "色深" },
    .Retro_Color_Bits    = { .EN = "Bits per channel",  .ZH = "每通道位数" },
    .Retro_Dither        = { .EN = "Dither",            .ZH = "抖动" },
    .Retro_Composite     = { .EN = "Composite blur",    .ZH = "复合视频模糊" },
    .Retro_Luma_Blur     = { .EN = "Luma blur",         .ZH = "亮度模糊" },
    .Retro_Chroma_Blur   = { .EN = "Chroma blur",       .ZH = "色度模糊" },
    .Retro_Scanlines     = { .EN = "Scanlines",         .ZH = "扫描线" },
    .Retro_Strength      = { .EN = "Strength",          .ZH = "强度" },
    .Retro_Beam_Dark     = { .EN = "Dark beam width",   .ZH = "暗部光束宽度" },
    .Retro_Beam_Bright   = { .EN = "Bright beam width", .ZH = "亮部光束宽度" },
    .Retro_Mask          = { .EN = "Aperture grille",   .ZH = "荫栅" },
    .Retro_Bloom         = { .EN = "Bloom",             .ZH = "泛光" },
    .Retro_Radius        = { .EN = "Radius",            .ZH = "半径" },
    .Retro_Tube          = { .EN = "Tube",              .ZH = "显像管" },
    .Retro_Gamma         = { .EN = "Gamma",             .ZH = "伽马" },
    .Retro_Gamma_Tip     = { .EN = "The tube's gamma: 2.2 is neutral, higher deepens the shadows", .ZH = "显像管伽马：2.2 为中性，越高阴影越深" },
    .Retro_Brightness    = { .EN = "Brightness",        .ZH = "亮度" },
    .Retro_Clean_Note    = { .EN = "Views in clean mode show none of this; turn on the retro look in their toolbar.", .ZH = "干净模式的视图不显示这些效果；请在其工具栏中开启复古效果。" },
    .Btn_Retro_Defaults  = { .EN = "Reset to Defaults", .ZH = "恢复默认" },
    .Bake_Last           = { .EN = "Last bake: %.2f s on %d threads · %d instances, %d lights · back faces %.1f%%, %d buried", .ZH = "上次烘焙：%.2f 秒，%d 个线程 · %d 个实例，%d 个光源 · 背面 %.1f%%，%d 个埋入" },
    .Bake_Atlas          = { .EN = "Probe atlas",       .ZH = "探针图集" },
    .Bake_Atlas_Tip      = { .EN = "Each probe is a tile of the light it gives a surface facing each way: centre up, edges the horizon, corners down. One block per layer, seen from above (+X right, +Z up), bottom layer first. Drawn at the exposure it was baked with.", .ZH = "每个探针是一个小块，显示朝向各方向的表面接收的光：中心朝上，边缘为水平方向，四角朝下。每层一个区块，俯视（+X 向右，+Z 向上），从最底层开始。按烘焙时的曝光绘制。" },
    .Tool_Lighting       = { .EN = "Lighting",          .ZH = "光照" },
    .Lighting_Lit           = { .EN = "Lit",            .ZH = "完整光照" },
    .Lighting_Probes_Only   = { .EN = "Probes Only",    .ZH = "仅探针" },
    .Lighting_Indirect_Only = { .EN = "Indirect Only",  .ZH = "仅间接光" },
    .Lighting_Direct_Only   = { .EN = "Direct Only",    .ZH = "仅直接光" },
    .Lighting_Lighting_Only = { .EN = "Lighting Only",  .ZH = "仅光照（白模）" },
    .Lighting_Use_Probes    = { .EN = "Use Baked Probes", .ZH = "使用烘焙探针" },
    .Lighting_Indirect_Scale = { .EN = "Indirect ×",    .ZH = "间接光倍数" },
    .Lighting_Reset         = { .EN = "Reset",          .ZH = "重置" },
    .Win_Game_Settings  = { .EN = "Game Settings###game_settings", .ZH = "游戏设置###game_settings" },
    .Menu_Game_Settings = { .EN = "Game Settings",  .ZH = "游戏设置" },
    .Game_Start_Level   = { .EN = "Start Level",    .ZH = "起始关卡" },

    .Win_Templates      = { .EN = "Templates###templates", .ZH = "模板###templates" },
    .Menu_Templates     = { .EN = "Templates",      .ZH = "模板" },
    .Templates_Hint     = { .EN = "Click to add to the active world.", .ZH = "点击添加到活动世界。" },
    .Templates_No_World = { .EN = "No world open — open a scene from the Worlds window.",
                            .ZH = "没有打开的世界 — 请在“世界”窗口中打开场景。" },
    .Btn_Edit_Templates = { .EN = "Edit Templates", .ZH = "编辑模板" },
    .Template_empty              = { .EN = "Empty",              .ZH = "空实体" },
    .Template_marker             = { .EN = "Marker",             .ZH = "标记" },
    .Template_point_light        = { .EN = "Point Light",        .ZH = "点光源" },
    .Template_point_light_shadow = { .EN = "Point Light (Shadow)", .ZH = "点光源（阴影）" },
    .Template_spot_light         = { .EN = "Spot Light",         .ZH = "聚光灯" },
    .Template_spot_light_shadow  = { .EN = "Spot Light (Shadow)", .ZH = "聚光灯（阴影）" },
    .Template_cylinder_light     = { .EN = "Cylinder Light",     .ZH = "圆柱光" },
    .Template_sun                = { .EN = "Sun",                .ZH = "太阳" },
    .Template_camera             = { .EN = "Camera",             .ZH = "相机" },
    .Template_ortho_camera       = { .EN = "Ortho Camera",       .ZH = "正交相机" },

    .Panel_Follow              = { .EN = "Follow active",        .ZH = "跟随活动视口" },
    .Panel_No_World            = { .EN = "No world open — open a scene or kit from the Worlds window.",
                                   .ZH = "没有打开的世界 — 请在“世界”窗口中打开场景或套件。" },
    .Inspector_Kit_Warning     = { .EN = "Opened from a kit — changes won't be saved.",
                                   .ZH = "从套件打开 — 更改不会被保存。" },

    .Win_Resources    = { .EN = "GPU Resources###resources", .ZH = "GPU 资源###resources" },
    .Menu_Resources   = { .EN = "GPU Resources",  .ZH = "GPU 资源" },
    .Res_Kind_Texture   = { .EN = "Textures",       .ZH = "纹理" },
    .Res_Kind_Geometry  = { .EN = "Geometry",       .ZH = "几何体" },
    .Res_Kind_Table     = { .EN = "Tables",         .ZH = "数据表" },
    .Res_Kind_Probes      = { .EN = "Probes",         .ZH = "探针" },
    .Res_Kind_Frame_Data  = { .EN = "Per-frame buffers", .ZH = "每帧缓冲区" },
    .Res_Kind_Target      = { .EN = "Render targets", .ZH = "渲染目标" },
    .Res_Owner_Assets     = { .EN = "Assets",         .ZH = "资源" },
    .Res_Owner_View       = { .EN = "View",           .ZH = "视图" },
    .Res_Owner_Engine     = { .EN = "Engine",         .ZH = "引擎" },
    .Res_Flights          = { .EN = "frames in flight", .ZH = "帧并行" },
    .Res_Transforms       = { .EN = "Transforms",     .ZH = "变换" },
    .Res_Mesh_Instances   = { .EN = "Mesh instances", .ZH = "网格实例" },
    .Res_Lights           = { .EN = "Lights",         .ZH = "光源" },
    .Res_Draw_Commands    = { .EN = "Draw commands",  .ZH = "绘制命令" },
    .Res_Shadow_Maps      = { .EN = "Shadow maps",    .ZH = "阴影贴图" },
    .Res_Shadow_Views     = { .EN = "Shadow cameras", .ZH = "阴影相机" },
    .Res_Probes           = { .EN = "Probe grid",     .ZH = "探针网格" },
    .Res_Probe_Depth      = { .EN = "Probe depth",    .ZH = "探针深度" },
    .Res_Display_Target   = { .EN = "Display target", .ZH = "显示目标" },
    .Res_Scene_Target     = { .EN = "Scene target (HDR)", .ZH = "场景目标（HDR）" },
    .Res_Depth_Target     = { .EN = "Depth",          .ZH = "深度" },
    .Res_Frame_Constants  = { .EN = "Frame constants", .ZH = "帧常量" },
    .Res_Swapchain        = { .EN = "Swapchain",      .ZH = "交换链" },
    .Res_Debug_Lines      = { .EN = "Debug lines",    .ZH = "调试线" },
    .Res_Count          = { .EN = "%d resources",   .ZH = "%d 个资源" },
    .Asset_Shared         = { .EN = "shared by %d keys", .ZH = "被 %d 个键共享" },
    .Asset_Mesh_Detail    = { .EN = "%d vertices, %d triangles", .ZH = "%d 个顶点，%d 个三角形" },
    .Asset_Mesh_Table     = { .EN = "Mesh table",     .ZH = "网格表" },
    .Asset_Material_Table = { .EN = "Material table", .ZH = "材质表" },

    .Ctx_Copy       = { .EN = "Copy",            .ZH = "复制" },
    .Ctx_Paste      = { .EN = "Paste",           .ZH = "粘贴" },
    .Ctx_Duplicate  = { .EN = "Duplicate",       .ZH = "创建副本" },
    .Ctx_Delete     = { .EN = "Delete",          .ZH = "删除" },
    .Ctx_Select_All = { .EN = "Select All",      .ZH = "全选" },
    .Ctx_Deselect   = { .EN = "Deselect",        .ZH = "取消选择" },
    .Ctx_Frame      = { .EN = "Frame Selection", .ZH = "聚焦所选" },
    .Ctx_Hide       = { .EN = "Hide",            .ZH = "隐藏" },
    .Ctx_Unhide_All = { .EN = "Unhide All",      .ZH = "全部取消隐藏" },

    .Play_Play          = { .EN = "Play",    .ZH = "运行" },
    .Play_Stop          = { .EN = "Stop",    .ZH = "停止" },
    .Play_Pause         = { .EN = "Pause",   .ZH = "暂停" },
    .Play_No_Save       = { .EN = "Can't save while playing — stop first.", .ZH = "运行中无法保存 — 请先停止。" },
    .Play_Warning       = { .EN = "Playing — changes are discarded on Stop.", .ZH = "运行中 — 停止后更改将被丢弃。" },
    .Worlds_Playing_Tag = { .EN = "playing", .ZH = "运行中" },
    .Ctx_Rename         = { .EN = "Rename",   .ZH = "重命名" },
    .Tool_Maximize      = { .EN = "Maximize", .ZH = "最大化" },
    .Play_Step          = { .EN = "Step one frame", .ZH = "单步一帧" },
    .Tool_Game_View     = { .EN = "Game View: hide icons, outlines and the gizmo", .ZH = "游戏视图：隐藏图标、轮廓和操纵器" },
    .Tool_Retro_Look    = { .EN = "Retro look: the PS1 and CRT effects set in the Retro Look window (off: clean full resolution)", .ZH = "复古效果：使用复古效果窗口中设置的 PS1 和 CRT 效果（关闭：干净的全分辨率）" },
    .Tool_Edit_Script   = { .EN = "Edit the world's Lua script in VS Code", .ZH = "在 VS Code 中编辑世界的 Lua 脚本" },
}

// Localized label for the current language, ready to hand straight to ImGui.
tr :: proc(id: Loc_ID) -> cstring {
    return loc_text[id][loc_lang]
}

// Same, as an Odin string — for composing into fmt.*printf.
trs :: proc(id: Loc_ID) -> string {
    return string(loc_text[id][loc_lang])
}

// Fail loudly at startup on a half-translated key (an unfilled cell is a nil cstring).
loc_verify :: proc() {
    for row, id in loc_text {
        for s, lang in row {
            if s == nil || s == "" {
                log.panicf("Missing localization: %v / %v", id, lang)
            }
        }
    }
}
